ALTER TABLE "BulkJob" ADD COLUMN "fileName" TEXT;
ALTER TABLE "BulkJob" ADD COLUMN "uploadedBy" TEXT;
ALTER TABLE "BulkJob" ADD COLUMN "successRows" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "BulkJob" ADD COLUMN "failedRows" INTEGER NOT NULL DEFAULT 0;
